# This is a sample build configuration for Go.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: golang:1.9

pipelines:
  default:
    - step:
        script: # Modify the commands below to build your repository.
          - PACKAGE_PATH="${GOPATH}/src/bitbucket.org/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}"
          - mkdir -pv "${PACKAGE_PATH}"
          - tar -cO --exclude-vcs --exclude=bitbucket-pipelines.yml . | tar -xv -C "${PACKAGE_PATH}"
          - cd "${PACKAGE_PATH}"

          - go get -v github.com/lib/pq
          - go get -v github.com/DATA-DOG/go-sqlmock
          - go get -v gopkg.in/DATA-DOG/go-sqlmock.v1
          - go get -v github.com/stretchr/testify/assert
          - go get -v github.com/appleboy/gin-jwt
          - go get -v github.com/gin-contrib/cors
          - go get -v github.com/gin-gonic/gin

          - go build -v backend/*.go
          - go test -v bitbucket.org/SealTV/go-site/backend/data
          - go test -bench=.  bitbucket.org/SealTV/go-site/tools